name = "ParallelIDMappingsBenchmarks"
uuid = "a28e0a30-fdcf-4e99-8b48-59bb73260860"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ParallelIDMappings = "5d3a874e-6454-4b32-9ce4-09d81493fc87"

[compat]
julia = "1.6"
